---
# This workflow executes several linters on changed files
# based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Lint Code Base

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        #https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v2.5.0
        #uses: actions/checkout@latest
        with:
          # Full git history is needed to get a proper list
          # of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        #https://github.com/marketplace/actions/super-linter
        #uses: github/super-linter@v4.9.7
        uses: github/super-linter@latest
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          PYTHON_BLACK_CONFIG_FILE: ./pyproject.toml
          PYTHON_ISORT_CONFIG_FILE: ./pyproject.toml
